const classes = [
    {
        id: 0,
        name: `warrior`,
        class: `Warrior`,
        hp: 100,
        mhp: 100,
        pAtk: 1,
        pDef: 1,
        mAtk: 1,
        mDef: 1,
        'starting-energy': 30,
        'max-energy': 100,
        roles: ['P. Dmg', 'Tank'],
        info: 'A hearty fighter that has strong physical attack and defense',
        image: 'https://opengameart.org/sites/default/files/warrior_f_attack.gif',
    },
    {   
        id: 1,
        name: 'wizard',
        class: 'Wizard',
        hp: 100,
        mhp: 100,
        pAtk: 1,
        pDef: 1,
        mAtk: 1,
        mDef: 1,
        'starting-energy': 30,
        'max-energy': 100,
        roles: ['M. Dmg', 'Support'],
        info: 'Crafty magic user that can cast damaging and supportive spells',
        image: 'https://opengameart.org/sites/default/files/wizard_walk.gif'
    },
    {   
        id: 2,
        name: 'rogue',
        class: 'Rogue',
        hp: 100,
        mhp: 100,
        pAtk: 1,
        pDef: 1,
        mAtk: 1,
        mDef: 1,
        'starting-energy': 30,
        'max-energy': 100,
        roles: ['P. Dmg', 'Debuffs'],
        info: 'Opportunist rogue that can hide and distract enemies while plotting when to strike',
        image: 'https://opengameart.org/sites/default/files/walk_10.gif'
    },
    {
        id: 3,
        name: 'cleric',
        class: `Cleric`,
        hp: 100,
        mhp: 100,
        pAtk: 1,
        pDef: 1,
        mAtk: 1,
        mDef: 1,
        'starting-energy': 30,
        'max-energy': 100,
        roles: ['Healing', 'Buffs'],
        info: 'Devout cleric that uses magic and medicine to support allies',
        image: 'https://opengameart.org/sites/default/files/cleric%20gesture.gif'
    }
]

export {classes}